name = "GeneNetworkAPI"
uuid = "5ef98721-7938-4c15-bad2-60f0fa16d62a"
authors = ["Chelsea Trotter <chelsea.xhu@gmail.com>",
	   "Gregory Farage <gfarage@uthsc.edu>",
	   "Saunak Sen <sen@uthsc.edu>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
